# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rotun-li/libgo-simple

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rotun-li/libgo-simple

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rotun-li/libgo-simple/CMakeFiles /home/rotun-li/libgo-simple/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rotun-li/libgo-simple/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_go_sync

# Build rule for target.
test_go_sync: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_go_sync
.PHONY : test_go_sync

# fast build rule for target.
test_go_sync/fast:
	$(MAKE) -f CMakeFiles/test_go_sync.dir/build.make CMakeFiles/test_go_sync.dir/build
.PHONY : test_go_sync/fast

#=============================================================================
# Target rules for targets named test_go

# Build rule for target.
test_go: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_go
.PHONY : test_go

# fast build rule for target.
test_go/fast:
	$(MAKE) -f CMakeFiles/test_go.dir/build.make CMakeFiles/test_go.dir/build
.PHONY : test_go/fast

#=============================================================================
# Target rules for targets named routine

# Build rule for target.
routine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 routine
.PHONY : routine

# fast build rule for target.
routine/fast:
	$(MAKE) -f CMakeFiles/routine.dir/build.make CMakeFiles/routine.dir/build
.PHONY : routine/fast

src/Config.o: src/Config.cpp.o

.PHONY : src/Config.o

# target to build an object file
src/Config.cpp.o:
	$(MAKE) -f CMakeFiles/routine.dir/build.make CMakeFiles/routine.dir/src/Config.cpp.o
.PHONY : src/Config.cpp.o

src/Config.i: src/Config.cpp.i

.PHONY : src/Config.i

# target to preprocess a source file
src/Config.cpp.i:
	$(MAKE) -f CMakeFiles/routine.dir/build.make CMakeFiles/routine.dir/src/Config.cpp.i
.PHONY : src/Config.cpp.i

src/Config.s: src/Config.cpp.s

.PHONY : src/Config.s

# target to generate assembly for a file
src/Config.cpp.s:
	$(MAKE) -f CMakeFiles/routine.dir/build.make CMakeFiles/routine.dir/src/Config.cpp.s
.PHONY : src/Config.cpp.s

src/FdManager.o: src/FdManager.cpp.o

.PHONY : src/FdManager.o

# target to build an object file
src/FdManager.cpp.o:
	$(MAKE) -f CMakeFiles/routine.dir/build.make CMakeFiles/routine.dir/src/FdManager.cpp.o
.PHONY : src/FdManager.cpp.o

src/FdManager.i: src/FdManager.cpp.i

.PHONY : src/FdManager.i

# target to preprocess a source file
src/FdManager.cpp.i:
	$(MAKE) -f CMakeFiles/routine.dir/build.make CMakeFiles/routine.dir/src/FdManager.cpp.i
.PHONY : src/FdManager.cpp.i

src/FdManager.s: src/FdManager.cpp.s

.PHONY : src/FdManager.s

# target to generate assembly for a file
src/FdManager.cpp.s:
	$(MAKE) -f CMakeFiles/routine.dir/build.make CMakeFiles/routine.dir/src/FdManager.cpp.s
.PHONY : src/FdManager.cpp.s

src/Fiber.o: src/Fiber.cpp.o

.PHONY : src/Fiber.o

# target to build an object file
src/Fiber.cpp.o:
	$(MAKE) -f CMakeFiles/routine.dir/build.make CMakeFiles/routine.dir/src/Fiber.cpp.o
.PHONY : src/Fiber.cpp.o

src/Fiber.i: src/Fiber.cpp.i

.PHONY : src/Fiber.i

# target to preprocess a source file
src/Fiber.cpp.i:
	$(MAKE) -f CMakeFiles/routine.dir/build.make CMakeFiles/routine.dir/src/Fiber.cpp.i
.PHONY : src/Fiber.cpp.i

src/Fiber.s: src/Fiber.cpp.s

.PHONY : src/Fiber.s

# target to generate assembly for a file
src/Fiber.cpp.s:
	$(MAKE) -f CMakeFiles/routine.dir/build.make CMakeFiles/routine.dir/src/Fiber.cpp.s
.PHONY : src/Fiber.cpp.s

src/Hook.o: src/Hook.cpp.o

.PHONY : src/Hook.o

# target to build an object file
src/Hook.cpp.o:
	$(MAKE) -f CMakeFiles/routine.dir/build.make CMakeFiles/routine.dir/src/Hook.cpp.o
.PHONY : src/Hook.cpp.o

src/Hook.i: src/Hook.cpp.i

.PHONY : src/Hook.i

# target to preprocess a source file
src/Hook.cpp.i:
	$(MAKE) -f CMakeFiles/routine.dir/build.make CMakeFiles/routine.dir/src/Hook.cpp.i
.PHONY : src/Hook.cpp.i

src/Hook.s: src/Hook.cpp.s

.PHONY : src/Hook.s

# target to generate assembly for a file
src/Hook.cpp.s:
	$(MAKE) -f CMakeFiles/routine.dir/build.make CMakeFiles/routine.dir/src/Hook.cpp.s
.PHONY : src/Hook.cpp.s

src/IoManager.o: src/IoManager.cpp.o

.PHONY : src/IoManager.o

# target to build an object file
src/IoManager.cpp.o:
	$(MAKE) -f CMakeFiles/routine.dir/build.make CMakeFiles/routine.dir/src/IoManager.cpp.o
.PHONY : src/IoManager.cpp.o

src/IoManager.i: src/IoManager.cpp.i

.PHONY : src/IoManager.i

# target to preprocess a source file
src/IoManager.cpp.i:
	$(MAKE) -f CMakeFiles/routine.dir/build.make CMakeFiles/routine.dir/src/IoManager.cpp.i
.PHONY : src/IoManager.cpp.i

src/IoManager.s: src/IoManager.cpp.s

.PHONY : src/IoManager.s

# target to generate assembly for a file
src/IoManager.cpp.s:
	$(MAKE) -f CMakeFiles/routine.dir/build.make CMakeFiles/routine.dir/src/IoManager.cpp.s
.PHONY : src/IoManager.cpp.s

src/Log.o: src/Log.cpp.o

.PHONY : src/Log.o

# target to build an object file
src/Log.cpp.o:
	$(MAKE) -f CMakeFiles/routine.dir/build.make CMakeFiles/routine.dir/src/Log.cpp.o
.PHONY : src/Log.cpp.o

src/Log.i: src/Log.cpp.i

.PHONY : src/Log.i

# target to preprocess a source file
src/Log.cpp.i:
	$(MAKE) -f CMakeFiles/routine.dir/build.make CMakeFiles/routine.dir/src/Log.cpp.i
.PHONY : src/Log.cpp.i

src/Log.s: src/Log.cpp.s

.PHONY : src/Log.s

# target to generate assembly for a file
src/Log.cpp.s:
	$(MAKE) -f CMakeFiles/routine.dir/build.make CMakeFiles/routine.dir/src/Log.cpp.s
.PHONY : src/Log.cpp.s

src/Scheduler.o: src/Scheduler.cpp.o

.PHONY : src/Scheduler.o

# target to build an object file
src/Scheduler.cpp.o:
	$(MAKE) -f CMakeFiles/routine.dir/build.make CMakeFiles/routine.dir/src/Scheduler.cpp.o
.PHONY : src/Scheduler.cpp.o

src/Scheduler.i: src/Scheduler.cpp.i

.PHONY : src/Scheduler.i

# target to preprocess a source file
src/Scheduler.cpp.i:
	$(MAKE) -f CMakeFiles/routine.dir/build.make CMakeFiles/routine.dir/src/Scheduler.cpp.i
.PHONY : src/Scheduler.cpp.i

src/Scheduler.s: src/Scheduler.cpp.s

.PHONY : src/Scheduler.s

# target to generate assembly for a file
src/Scheduler.cpp.s:
	$(MAKE) -f CMakeFiles/routine.dir/build.make CMakeFiles/routine.dir/src/Scheduler.cpp.s
.PHONY : src/Scheduler.cpp.s

src/Thread.o: src/Thread.cpp.o

.PHONY : src/Thread.o

# target to build an object file
src/Thread.cpp.o:
	$(MAKE) -f CMakeFiles/routine.dir/build.make CMakeFiles/routine.dir/src/Thread.cpp.o
.PHONY : src/Thread.cpp.o

src/Thread.i: src/Thread.cpp.i

.PHONY : src/Thread.i

# target to preprocess a source file
src/Thread.cpp.i:
	$(MAKE) -f CMakeFiles/routine.dir/build.make CMakeFiles/routine.dir/src/Thread.cpp.i
.PHONY : src/Thread.cpp.i

src/Thread.s: src/Thread.cpp.s

.PHONY : src/Thread.s

# target to generate assembly for a file
src/Thread.cpp.s:
	$(MAKE) -f CMakeFiles/routine.dir/build.make CMakeFiles/routine.dir/src/Thread.cpp.s
.PHONY : src/Thread.cpp.s

src/Timer.o: src/Timer.cpp.o

.PHONY : src/Timer.o

# target to build an object file
src/Timer.cpp.o:
	$(MAKE) -f CMakeFiles/routine.dir/build.make CMakeFiles/routine.dir/src/Timer.cpp.o
.PHONY : src/Timer.cpp.o

src/Timer.i: src/Timer.cpp.i

.PHONY : src/Timer.i

# target to preprocess a source file
src/Timer.cpp.i:
	$(MAKE) -f CMakeFiles/routine.dir/build.make CMakeFiles/routine.dir/src/Timer.cpp.i
.PHONY : src/Timer.cpp.i

src/Timer.s: src/Timer.cpp.s

.PHONY : src/Timer.s

# target to generate assembly for a file
src/Timer.cpp.s:
	$(MAKE) -f CMakeFiles/routine.dir/build.make CMakeFiles/routine.dir/src/Timer.cpp.s
.PHONY : src/Timer.cpp.s

src/Util.o: src/Util.cpp.o

.PHONY : src/Util.o

# target to build an object file
src/Util.cpp.o:
	$(MAKE) -f CMakeFiles/routine.dir/build.make CMakeFiles/routine.dir/src/Util.cpp.o
.PHONY : src/Util.cpp.o

src/Util.i: src/Util.cpp.i

.PHONY : src/Util.i

# target to preprocess a source file
src/Util.cpp.i:
	$(MAKE) -f CMakeFiles/routine.dir/build.make CMakeFiles/routine.dir/src/Util.cpp.i
.PHONY : src/Util.cpp.i

src/Util.s: src/Util.cpp.s

.PHONY : src/Util.s

# target to generate assembly for a file
src/Util.cpp.s:
	$(MAKE) -f CMakeFiles/routine.dir/build.make CMakeFiles/routine.dir/src/Util.cpp.s
.PHONY : src/Util.cpp.s

src/libco/coctx.o: src/libco/coctx.cpp.o

.PHONY : src/libco/coctx.o

# target to build an object file
src/libco/coctx.cpp.o:
	$(MAKE) -f CMakeFiles/routine.dir/build.make CMakeFiles/routine.dir/src/libco/coctx.cpp.o
.PHONY : src/libco/coctx.cpp.o

src/libco/coctx.i: src/libco/coctx.cpp.i

.PHONY : src/libco/coctx.i

# target to preprocess a source file
src/libco/coctx.cpp.i:
	$(MAKE) -f CMakeFiles/routine.dir/build.make CMakeFiles/routine.dir/src/libco/coctx.cpp.i
.PHONY : src/libco/coctx.cpp.i

src/libco/coctx.s: src/libco/coctx.cpp.s

.PHONY : src/libco/coctx.s

# target to generate assembly for a file
src/libco/coctx.cpp.s:
	$(MAKE) -f CMakeFiles/routine.dir/build.make CMakeFiles/routine.dir/src/libco/coctx.cpp.s
.PHONY : src/libco/coctx.cpp.s

src/libco/coctx_swap.o: src/libco/coctx_swap.S.o

.PHONY : src/libco/coctx_swap.o

# target to build an object file
src/libco/coctx_swap.S.o:
	$(MAKE) -f CMakeFiles/routine.dir/build.make CMakeFiles/routine.dir/src/libco/coctx_swap.S.o
.PHONY : src/libco/coctx_swap.S.o

test/test_go.o: test/test_go.cpp.o

.PHONY : test/test_go.o

# target to build an object file
test/test_go.cpp.o:
	$(MAKE) -f CMakeFiles/test_go.dir/build.make CMakeFiles/test_go.dir/test/test_go.cpp.o
.PHONY : test/test_go.cpp.o

test/test_go.i: test/test_go.cpp.i

.PHONY : test/test_go.i

# target to preprocess a source file
test/test_go.cpp.i:
	$(MAKE) -f CMakeFiles/test_go.dir/build.make CMakeFiles/test_go.dir/test/test_go.cpp.i
.PHONY : test/test_go.cpp.i

test/test_go.s: test/test_go.cpp.s

.PHONY : test/test_go.s

# target to generate assembly for a file
test/test_go.cpp.s:
	$(MAKE) -f CMakeFiles/test_go.dir/build.make CMakeFiles/test_go.dir/test/test_go.cpp.s
.PHONY : test/test_go.cpp.s

test/test_go_sync.o: test/test_go_sync.cpp.o

.PHONY : test/test_go_sync.o

# target to build an object file
test/test_go_sync.cpp.o:
	$(MAKE) -f CMakeFiles/test_go_sync.dir/build.make CMakeFiles/test_go_sync.dir/test/test_go_sync.cpp.o
.PHONY : test/test_go_sync.cpp.o

test/test_go_sync.i: test/test_go_sync.cpp.i

.PHONY : test/test_go_sync.i

# target to preprocess a source file
test/test_go_sync.cpp.i:
	$(MAKE) -f CMakeFiles/test_go_sync.dir/build.make CMakeFiles/test_go_sync.dir/test/test_go_sync.cpp.i
.PHONY : test/test_go_sync.cpp.i

test/test_go_sync.s: test/test_go_sync.cpp.s

.PHONY : test/test_go_sync.s

# target to generate assembly for a file
test/test_go_sync.cpp.s:
	$(MAKE) -f CMakeFiles/test_go_sync.dir/build.make CMakeFiles/test_go_sync.dir/test/test_go_sync.cpp.s
.PHONY : test/test_go_sync.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test_go_sync"
	@echo "... test_go"
	@echo "... routine"
	@echo "... src/Config.o"
	@echo "... src/Config.i"
	@echo "... src/Config.s"
	@echo "... src/FdManager.o"
	@echo "... src/FdManager.i"
	@echo "... src/FdManager.s"
	@echo "... src/Fiber.o"
	@echo "... src/Fiber.i"
	@echo "... src/Fiber.s"
	@echo "... src/Hook.o"
	@echo "... src/Hook.i"
	@echo "... src/Hook.s"
	@echo "... src/IoManager.o"
	@echo "... src/IoManager.i"
	@echo "... src/IoManager.s"
	@echo "... src/Log.o"
	@echo "... src/Log.i"
	@echo "... src/Log.s"
	@echo "... src/Scheduler.o"
	@echo "... src/Scheduler.i"
	@echo "... src/Scheduler.s"
	@echo "... src/Thread.o"
	@echo "... src/Thread.i"
	@echo "... src/Thread.s"
	@echo "... src/Timer.o"
	@echo "... src/Timer.i"
	@echo "... src/Timer.s"
	@echo "... src/Util.o"
	@echo "... src/Util.i"
	@echo "... src/Util.s"
	@echo "... src/libco/coctx.o"
	@echo "... src/libco/coctx.i"
	@echo "... src/libco/coctx.s"
	@echo "... src/libco/coctx_swap.o"
	@echo "... test/test_go.o"
	@echo "... test/test_go.i"
	@echo "... test/test_go.s"
	@echo "... test/test_go_sync.o"
	@echo "... test/test_go_sync.i"
	@echo "... test/test_go_sync.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

